# Generated by Django 5.0.1 on 2024-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('number_of_reviews', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('plays', models.CharField(max_length=255)),
                ('playing', models.CharField(max_length=255)),
                ('ratio_confiance', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
