# Generated by Django 5.0.1 on 2024-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stem_summary',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
