# Generated by Django 5.0.1 on 2024-02-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_stem_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='overall_mean_score',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
